language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
before_script:
  - npm install babel-core@7.0.0-bridge.0 # Fixme. Wait for babel-jest update
script:
  - npm run lint:css
  - npm run lint:ts
  - npm test
